version: '2'

services:
  db:
    environment:
      POSTGRES_DB: dfs
    expose:
      - 5432
    image: postgres:9.6.1-alpine

  auth-service:
    command: wait-for-it.sh migrator:8000 --strict -- auth-service
    depends_on:
      - db
      - migrator
    image: houli/auth-service
    ports:
      - "8080:8080"

  file-service:
    command: wait-for-it.sh migrator:8000 --strict -- file-service
    depends_on:
      - auth-service
      - db
      - directory-service
      - migrator
    image: houli/file-service
    ports:
      - "8081:8081"

  directory-service:
    command: wait-for-it.sh migrator:8000 --strict -- directory-service
    depends_on:
      - auth-service
      - db
      - migrator
    image: houli/directory-service
    ports:
      - "8082:8082"

  migrator:
    command: wait-for-it.sh db:5432 --strict -- migrator
    depends_on:
      - db
    expose:
      - 8000
    image: houli/migrator
