version: '2'
services:
  db:
    environment:
      POSTGRES_DB: dfs
    expose:
      - 5432
    image: postgres:9.6.1-alpine
  auth-service:
    depends_on:
      - db
    environment:
      TOKEN_SECRET:
    image: auth-service-auth-service
    ports:
      - "8080:8080"
