version: '2'

networks:
  file-services:

volumes:
  postgres-data:
  fs1:
  fs2:
  fs3:

services:
  db:
    environment:
      POSTGRES_DB: dfs
    image: postgres:9.6.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data

  auth-service:
    command: wait-for-it.sh migrator:8000 --strict -- auth-service
    depends_on:
      - db
      - migrator
    image: houli/auth-service
    ports:
      - "8080:8080"

  file-service1:
    command: wait-for-it.sh directory-service:8080 --strict -- file-service
    depends_on:
      - auth-service
      - db
      - directory-service
      - migrator
    image: houli/file-service
    environment:
      EXPOSED_PORT: 8081
    networks:
      - default
      - file-services
    ports:
      - "8081:8080"
    volumes:
      - fs1:/data/files

  file-service2:
    command: wait-for-it.sh directory-service:8080 --strict -- file-service
    depends_on:
      - auth-service
      - db
      - directory-service
      - migrator
    image: houli/file-service
    environment:
      EXPOSED_PORT: 8082
    networks:
      - default
      - file-services
    ports:
      - "8082:8080"
    volumes:
      - fs2:/data/files

  file-service3:
    command: wait-for-it.sh directory-service:8080 --strict -- file-service
    depends_on:
      - auth-service
      - db
      - directory-service
      - migrator
    image: houli/file-service
    environment:
      EXPOSED_PORT: 8083
    networks:
      - default
      - file-services
    ports:
      - "8083:8080"
    volumes:
      - fs3:/data/files

  directory-service:
    command: wait-for-it.sh migrator:8000 --strict -- directory-service
    depends_on:
      - auth-service
      - db
      - migrator
    image: houli/directory-service
    ports:
      - "8084:8080"

  migrator:
    command: wait-for-it.sh db:5432 --strict -- migrator
    depends_on:
      - db
    expose:
      - 8000
    image: houli/migrator
