* File Service
** Overview
There are 3 main functions provided by the file service. These are the ability
to read files, write to files and to receive replication requests from other
file service nodes.

** Reading a File
A user client will have first queried the directory service to determine the
location of a file in the system. Using this node information it can now request
from the node the ability to read that file. Reading a file essentially amounts
to returning the base64 encoded contents of the file.

Base64 is used as an example in this system of the capability to "encrypt"
files. In a production environment outside of a pedagogical setting it would
make more sense to leverage more advanced techniques such as asymmetric
cryptography using key pairs to share files. However, this implementation is a
proof of concept of applying some kind of processing to the data being sent
across the wire so as to provide a framework for more secure implementations
building on top of the existing work.

** Writing to a File
Very much similar to reading from a file, writing to a file occurs on a single
primary node. Again base64 encoded contents are sent to the file system which
will decode and store the raw file contents. Other pertinent information such as
file sizes should also be reflected in the database representation of the file
and care is taken to appropriately update metadata of existing files in the case
of writing to a file that already existed on this primary.

Where the implementation differs from reading is the need to replicate the file
information to 1 or more other file nodes so that redundancy is introduced
should this primary die or become unreachable by other services. This is
explained in the next section.
