#+SETUPFILE: readthe.org
#+TITLE: Distributed File System
#+AUTHOR: Eoin Houlihan - 13323304
The goal of this project was to create a distributed file system. In this report
I outline my approach to the high-level system design of the file system
including technology used and system architecture. The individual sections
detail the more intricate aspects of the implementation of each of the systems
and gives justification for specific decisions made and the advantages and
tradeoffs caused by these decisions.

Included in the source code repository is the source for my authentication,
directory, file and migrator services. Also included is a FUSE based file system
driver that can be used to access my file system at the operating system level.
Lastly, a set of useful scripts and this documentation is also included.

#+INCLUDE: design.org
#+INCLUDE: authentication.org
#+INCLUDE: directory.org
#+INCLUDE: fileservice.org
#+INCLUDE: locking.org
#+INCLUDE: fusefsdriver.org
#+INCLUDE: migrator.org
#+INCLUDE: docker.org
#+INCLUDE: compileandrun.org
#+INCLUDE: screenshots.org
